configName: sam_9x60_ek_iar
folderName: ''
format_version: v1.0
frameworkPath: D:\H3
processor: SAM9X60
projectName: sqi_flash_fat_sam_9x60_ek
settings:
  PackageFilter: bsp;core;csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  DFPPath: .\dev_packs\Microchip\SAM9X60_DFP\1.0.5\atdf\SAM9X60.atdf
  MERGE_STRATEGY: USER_ALL
