configName: sam_9x60_ek_freertos_iar
folderName: ''
format_version: v1.0
frameworkPath: D:\MCU_MPU\SAMA5\H3_MPU
processor: SAM9X60
projectName: usart_multi_instance_sam_9x60_ek_freertos
settings:
  PackageFilter: bsp;core;csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  DFPPath: .\dev_packs\Microchip\SAM9X60_DFP\1.1.23\atdf\SAM9X60.atdf
  MERGE_STRATEGY: OVERWRITE
