configName: sam_9x60_ek_freertos_iar
folderName: ''
format_version: v1.0
frameworkPath: D:\Projects\mpu
processor: SAM9X60
projectName: sdmmc_fat_sam_9x60_ek_freertos
settings:
  PackageFilter: bsp;core;csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  DFPPath: .\dev_packs\Microchip\SAM9X60_DFP\0.1.14\atdf\SAM9X60.atdf
  MERGE_STRATEGY: OVERWRITE
