format_version: v1.0
type: UniqueComponent
attributes: {id: drv_nand_flash}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: DRV_NAND_FLASH_CHIP_SELECT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_nand_flash, value: '3'}
  - type: String
    attributes: {id: DRV_NAND_FLASH_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_nand_flash, value: SMC}
  - type: Boolean
    attributes: {id: DRV_NAND_FLASH_TX_RX_DMA}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: DRV_NAND_FLASH_TX_RX_DMA_CHANNEL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_nand_flash, value: '0'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: drv_nand_flash_NAND_CS_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: smc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: smc_cs3}
- type: ElementPosition
  attributes: {x: '460', y: '20', id: drv_nand_flash}
