configName: sam_9x60_ek
folderName: ''
format_version: v1.0
frameworkPath: ../../../../..
processor: SAM9X60
projectName: ''
settings:
  PackageFilter: bsp;core;csp;csp_apps_pic32cm_jh00_jh01;csp_apps_pic32cm_le00_ls00;expresslogic_threadx;mbed_os;micrium_ucos3;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  DFPPath: .\dev_packs\Microchip\SAM9X60_DFP\1.2.31\atdf\SAM9X60.atdf
  MERGE_STRATEGY: USER_ALL
