configName: sam_9x60_curiosity
folderName: sam_9x60_curiosity
format_version: v1.0
frameworkPath: ..\..\..\..\..\..\harmony_3
processor: SAM9X60
projectName: ram_fat_sam_9x60_curiosity
settings:
  PackageFilter: bootloader;bsp;core;csp;net;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAM9X60_DFP\1.6.54\atdf\SAM9X60.atdf
